### ISSUE TITLE
Badly formatted badge metadata produces poor visual experience

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/crates.io#1303]
From the ical crate: 

```toml
[badges.travis-ci]
branch = "master"
repository = "https://travis-ci.org/Peltoche/ical-rs"
```

produces: 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/573215/38203908-a9593502-3655-11e8-9f90-7ac5b143da3f.png">
