### ISSUE TITLE
Cannot publish packages that enable features in dependencies (regression)

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/crates.io#1334]
Hi, I'm trying to publish a crate that contains the following in its `Cargo.toml`

```toml
[features]
nightly = ["radix_51", "subtle/nightly", "clear_on_drop/nightly"]
```

to enable `nightly` features in dependencies.  However, it's no longer possible to publish this crate to `crates.io`, since it fails with:
```
error: api errors: invalid upload request: invalid value: string "subtle/nightly", expected a valid feature name at line 1 column 2315
```

This appears to be the error generated by [this code](https://github.com/rust-lang/crates.io/blob/master/src/views/krate_publish.rs#L126), and the same `Cargo.toml` was accepted up until a few days ago, so my guess is that this is a recent regression?
