### ISSUE TITLE
Incorrect metadata coming from last published version

### ISSUE THREAD

**Issue by kvark** [rust-lang/crates.io#1389]
Case in question: https://crates.io/crates/io-surface

The "Repository" link under "io-surface 0.10.0" at the top is pointing to "https://github.com/servo/io-surface-rs", which is wrong. The repository was moved after 0.9, and the actual `Cargo.toml` for 0.10.0 has:
```toml
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.10.0"
```

@jrmuizel suspects "crates.io" got confused because 0.9.1 was published last. This seems like a bug in the web site.
