### ISSUE TITLE
Inconsistency between crate file and www

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#1624]
https://crates.io/crates/rst has links to homepage, custom documentation, and repository.

However, the crate file from https://crates.io/api/v1/crates/rst/0.2.0/download contains `Cargo.toml` with only:

```toml
[package]
name = 'rst'
version = '0.2.0'
authors = [ 'Phil Schaf <flying-sheep@web.de>' ]

[dependencies]
url = '0.5'
bitflags = '0.5'
unicode_categories = '0.1.0'
```

This is very surprising. Where did these links come from?
