### ISSUE TITLE
Not helpful message on missing dependency version

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/crates.io#1627]
In this case:

```toml
[build-dependencies.gtk-rs-lgpl-docs]
optional = true
```

If you try to publish a crate using something along the line you get:

```
error: api errors: wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```

Therefore, users look for a "*" and not a missing version, which is quite bad.
