### ISSUE TITLE
Travis badges are not shown for the crates with `-` in the name.

### ISSUE THREAD

**Issue by vityafx** [rust-lang/crates.io#1767]
Today I have found out that that travis badges specified in the `Cargo.toml` file as this:

```toml
[badges]
travis-ci = { repository = "vityafx/diesel-chrono-duration" }
```

are not shown on the crate's page on the crates.io. Examples are: [grammarly](https://crates.io/crates/grammarly) and [diesel-chrono-duration](https://crates.io/crates/diesel-chrono-duration).
