### ISSUE TITLE
Show list of crate features

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/crates.io#3355]
![image](https://user-images.githubusercontent.com/10433001/109478859-bab41c80-7ab4-11eb-89e0-281ec98592d3.png)
 
add features with website,that can quick preview. for example with tokio features:

```toml
[features]
default = []
fs = []
full = ["fs", "io-util", "io-std", "macros", "net", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "sync", "time"]
io-std = []
io-util = ["memchr", "bytes"]
macros = ["tokio-macros"]
net = ["libc", "mio/os-poll", "mio/os-util", "mio/tcp", "mio/udp", "mio/uds"]
process = ["bytes", "once_cell", "libc", "mio/os-poll", "mio/os-util", "mio/uds", "signal-hook-registry", "winapi/threadpoollegacyapiset"]
rt = []
rt-multi-thread = ["num_cpus", "rt"]
signal = ["once_cell", "libc", "mio/os-poll", "mio/uds", "mio/os-util", "signal-hook-registry", "winapi/consoleapi"]
sync = []
test-util = []
time = []
[target."cfg(loom)".dev-dependencies.loom]
version = "0.4"
features = ["futures", "checkpoint"]
[target."cfg(tokio_unstable)".dependencies.tracing]
version = "0.1.21"
features = ["std"]
optional = true
default-features = false
[target."cfg(unix)".dependencies.libc]
version = "0.2.42"
optional = true
```
