### ISSUE TITLE
Wrong readme link resolution for relative paths with workspace readme

### ISSUE THREAD

**Issue by beeb** [rust-lang/crates.io#9927]
### Current Behavior

Consider a repository at `https://github.com/foo/bar.git`.

The `README.md` file at the root contains the following:

```markdown
See [this file](./thisfile.md)
```

The root `Cargo.toml` contains:

```toml
[workspace]
members = ["crates/mycrate"]
resolver = "2"

[workspace.package]
readme = "./README.md"
```

The `crates/mycrate/Cargo.toml`:

```toml
[package]
# ...
readme.workspace = true
```

In that case, the README on crates.io will resolve the link to `https://github.com/foo/bar/blob/HEAD/crates/mycrate/thisfile.md`.

### Expected Behavior

The link in the README on crates.io should resolve to `https://github.com/foo/bar/blob/HEAD/thisfile.md`.

### Steps To Reproduce

See setup in the "Current Behavior" section.

### Environment

- Browser: N/A
- OS: N/A

### Anything else?

The same problem appears with relative images.
